use_frameworks!

target 'EHCollectionViewFixedInteritemSpacingLayout_Example' do
  pod 'EHCollectionViewFixedInteritemSpacingLayout', :path => '../'
  pod 'Masonry', '~> 0.6.4'

  target 'EHCollectionViewFixedInteritemSpacingLayout_Tests' do
    inherit! :search_paths

    
  end
end
